apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: my-project-dev
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: my-project
    app.kubernetes.io/managed-by: aaof
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  # Use ClusterIP for internal services.
  # Use NodePort for Minikube local access.
  # Use LoadBalancer for cloud external access.
  type: ClusterIP
